### PR TITLE
delete all perror/return pairs and created exceptions

### LINKED ISSUE #26: Replace error return with throw exception

### PR DESCRIPTION
**Pull request by Neffi42**

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -17,16 +19,23 @@ static void register_action(int signal, struct sigaction* old,
...
+		std::cerr << "cannot create signal action" << std::endl;
+		return -1;
 	}
+	return 0;
 }
 
 int main() {
-	register_action(SIGINT, NULL, &handle_singint);
-	register_action(SIGQUIT, NULL, SIG_IGN);
+	if (register_action(SIGINT, NULL, &handle_singint) == -1 ||
```
Comment (croueAlec) [inline src/main.cpp:29]: Would a try catch be overzealous here ?

**Comment by croueAlec** [comment]
```{
	"Exception": {
		"prefix": ["exception"],
		"body": [
			"class ${1:$BLOCK_COMMENT_START exception name $BLOCK_COMMENT_END} : public std::exception {",
			"  public:",
			"\tvirtual const char* what() const throw();",
			"};",
			"const char* $TM_FILENAME_BASE::${1:$BLOCK_COMMENT_START name $BLOCK_COMMENT_END}::what() const throw() {",
			"\treturn \"${2:$BLOCK_COMMENT_START error message $BLOCK_COMMENT_END}\";",
			"}"
		],
		"description": "Auto exception :sunglasses:"
	}
}```

**Review by antoineverin — APPROVED** [review]

**Review by croueAlec — APPROVED** [review]
